CHECKMETA = {
	["Player"] = IsValid,
	["Entity"] = IsValid,
	["table"] = true,
}

GAMETYPES = {}
TEAM_TRANSLATE = {}
POWERUPS = {}
POWERUP_TITLE = {}
POWERUP_IMAGE = {}

DEFAULT_PL_SPEED = 150
DEFAULT_PL_FREEZE_SPEED = 20

TEAM_PLAYERS = 0
TEAM_BLUE = 1
TEAM_RED = 2
TEAM_DEATHMATCH = 3

TEAM_TRANSLATE[TEAM_PLAYERS] = "Spectators"
TEAM_TRANSLATE[TEAM_BLUE] = "Blue Team"
TEAM_TRANSLATE[TEAM_RED] = "Red Team"
TEAM_TRANSLATE[TEAM_DEATHMATCH] = "Players"

team.SetUp(TEAM_BLUE, TEAM_TRANSLATE[TEAM_BLUE], COLOR_BLUE)
team.SetUp(TEAM_RED, TEAM_TRANSLATE[TEAM_RED], COLOR_RED)
team.SetUp(TEAM_DEATHMATCH, TEAM_TRANSLATE[TEAM_DEATHMATCH], COLOR_RED)
team.SetUp(TEAM_PLAYERS, TEAM_TRANSLATE[TEAM_PLAYERS], COLOR_GREEN, true)

WAIT_TIME = 45
WAIT_END = 15

STATE_WAITING = 0
STATE_PLAYING = 1
STATE_ENDING = 2

POWERUPS = {
	POWERUP_FAST = "powerfast",
	POWERUP_FIRE = "powerfire",
	POWERUP_FREEZE = "powerfreeze",
	POWERUP_POWERSHOT = "powershot",
	POWERUP_TRIPLESHOT = "powertriple"
}

POWERUP_TITLE[POWERUPS["POWERUP_FAST"]] = "Fast Shot"
POWERUP_TITLE[POWERUPS["POWERUP_FIRE"]] = "Fire Shot"
POWERUP_TITLE[POWERUPS["POWERUP_FREEZE"]] = "Freeze Shot"
POWERUP_TITLE[POWERUPS["POWERUP_POWERSHOT"]] = "Power Shot"
POWERUP_TITLE[POWERUPS["POWERUP_TRIPLESHOT"]] = "Triple Shot"