TEAM_PLAYERS = 0
TEAM_BLUE = 1
TEAM_RED = 2
TEAM_DEATHMATCH = 3

TEAM_TRANSLATE = {}
TEAM_TRANSLATE[TEAM_PLAYERS] = "Spectators"
TEAM_TRANSLATE[TEAM_BLUE] = "Blue Team"
TEAM_TRANSLATE[TEAM_RED] = "Red Team"
TEAM_TRANSLATE[TEAM_DEATHMATCH] = "Players"

team.SetUp(TEAM_BLUE, TEAM_TRANSLATE[TEAM_BLUE], COLOR_BLUE)
team.SetUp(TEAM_RED, TEAM_TRANSLATE[TEAM_RED], COLOR_RED)
team.SetUp(TEAM_DEATHMATCH, TEAM_TRANSLATE[TEAM_DEATHMATCH], COLOR_RED)
team.SetUp(TEAM_PLAYERS, TEAM_TRANSLATE[TEAM_PLAYERS], COLOR_GREEN, true)

GAMETYPE_DEATHMATCH = 1
GAMETYPE_TEAMDEATHMATCH = 2

GAMETYPE_TRANSLATE = {}
GAMETYPE_TRANSLATE[GAMETYPE_DEATHMATCH] = "Deathmatch"
GAMETYPE_TRANSLATE[GAMETYPE_TEAMDEATHMATCH] = "Team Deathmatch"

DEATHMATCH_TIMELIMIT = 300
DEATHMATCH_FRAGLIMIT = 10

POWERUP_NONE = 0
POWERUP_FREEZE = 1
POWERUP_FIRE = 2
POWERUP_POWERSHOT = 3
POWERUP_FAST = 4

POWERUP_TITLE = {}
POWERUP_TITLE[POWERUP_NONE] = "Normal"
POWERUP_TITLE[POWERUP_FREEZE] = "Freeze Shot"
POWERUP_TITLE[POWERUP_FIRE] = "Fire Shot"
POWERUP_TITLE[POWERUP_POWERSHOT] = "Power Shot"
POWERUP_TITLE[POWERUP_FAST] = "Fast Shot"